[mgr]

show_symlink = false
linemode = "size"
show_hidden = true

[opener]
open = [
    { run = 'opener "$@"', block = true, desc = "Open" },
]
alt = [
    { run = 'opener "$@"', block = true, desc = "Alt" },
]
nothing = [
    { run = 'echo -n', desc = "" },
]

[open]
rules = [
    { name = "*/", use = [ "nothing" ] },
    { mime = "*", use = [ "open", "alt" ] },
]

[plugin]
prepend_previewers = [
    # Default json previewer not working for some reason
    { mime = "application/{json,ndjson}", run = "code" },
]

