[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5b6268"
blue = "#3071db"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "0xbbc2cf"
yellow = "#da8548"

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 0.97
title = "Alacritty"

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
working_directory = "none"
